version: '3.7'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/usr/src/web/static

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: prod.Dockerfile
    command: gunicorn awm.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    stdin_open: true
    depends_on: 
        - db
    volumes:
      - static_volume:/usr/src/web/static
  
  db:
    container_name: psql
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    
volumes:
  postgres_data:      
  static_volume: